name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1
      uses: docker/build-push-action@v6.16.0
      with:
        context: .
        # Path to the Dockerfile
        file: aspects/terraform-module-promise/Dockerfile
        # List of metadata for an image
        # List of tags
        tags: ghcr.io/phiph/terraform-generate:latest
        # GitHub Token used to authenticate against a repository for Git context
        github-token: ${{ github.token }}
          
